[package]
name = "observatory-new"
version = "0.1.0"
authors = ["Steven vanZyl <rushsteve1@rushsteve1.us>"]
edition = "2018"

[dependencies]
askama = { version = "^0.8.0", features = ["with-rocket"] }
rocket = "^0.4.0"
diesel = { version = "^1.4.2", features = ["sqlite"] }

# By using * we match the Rocket versions
ring = "*"
serde = "*"
serde_derive = "*"

[dependencies.rocket_contrib]
version = "^0.4.0"
default-features = false
features = ["diesel_sqlite_pool", "json"]