[global.databases]
sqlite_observ = { url = "./observ.sqlite" }

[development]
address = "localhost"
port = 8000
log = "normal"

[production]
address = "0.0.0.0"
port = 80
log = "critical"
# Make sure to generate a secret key using:
# $ openssl rand -base64 32
# Put it here then uncomment line
# secret_key = generated key