version: 2

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly

    steps:
      - checkout
      - restore_cache:
          key: observatory-cache

      - run:
          name: Nightly Build
          command: "cargo build --all"

      - run:
          name: Unit Tests
          command: "cargo test --all"

      - save_cache:
          key: observatory-cache
          paths:
            - "~/.cargo"
            - "./target"
